services:
  - type: web
    name: django-quiz-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py makemigrations && python manage.py migrate && gunicorn quiz_app.wsgi:application
